name: "CI"
on:
  push:
    branches: [ main ]
jobs:
  generate_pdf:
    name: Upload resume pdf
    uses: actions/upload-artifact@v3.1.2
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    # with:
    #   # Artifact name
    #   name: resume.pdf # optional, default is artifact
    #   # A file, directory or wildcard pattern that describes what to upload
    #   path: ./index.html
