name: "CI"
on:
  push:
    branches: [ main ]
jobs:
  generate_pdf:
    name: Upload resume pdf
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    # with:
    #   # Artifact name
    #   name: resume.pdf # optional, default is artifact
    #   # A file, directory or wildcard pattern that describes what to upload
    #   path: ./index.html
