name: "CI"
on:
  push:
    branches: [ main ]
jobs:
  generate_pdf:
    name: Generate Resume PDF
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Generate PDF
      uses: LukaszLapaj/html-to-pdf-action@2.0.0
      with:
        htmlFile: ./index.html
        outputFile: ./resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: ./resume.pdf

