name: "CI"
on:
  push:
    branches: [ main ]
jobs:
  generate_pdf:
    name: Generate Resume PDF
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Generate PDF
      uses: LukaszLapaj/html-to-pdf-action@2.0.0
      with:
        htmlFile: ./index.html
        outputFile: ./resume.pdf
        pdfOptions: '{"format": "Letter"}'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date --iso-8601=minutes)"
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ steps.date.outputs.date }}
        files: ./resume.pdf

